site_name: rapidstats API Reference
site_url: https://cangyuanli.github.io/rapidstats/
repo_url: https://github.com/CangyuanLi/rapidstats

use_directory_urls: false

nav:
- Home: index.md
- Bootstrap: bootstrap.md
- Correlation: correlation.md
- Distributions: distributions.md
- Metrics: metrics.md

theme:
  name: material
  locale: en
  highlightjs: true
  features:
    - content.code.copy

plugins:
- search
- section-index
- mkdocstrings:
    handlers:
      python:
        paths: [python]
        options:
          summary: true
          docstring_style: numpy

markdown_extensions:
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra:
  version:
    provider: mike
